config/routes.rb
Rails.application.routes.draw do
  resources :emergency_transfer, only: [:index, :show]

  root to: "emergency_transfer#index"
end

app/models/admission.rb
class Admission < ApplicationRecord

  #
  ##Associations
  #
  belongs_to :patient

  has_many(
    :symptoms,
    dependent: :destroy
  )

  has_many(
    :observations,
    dependent: :destroy
  )

  has_many :diagnoses, -> { where(diagnosis_type: 1)}, class_name: 'Diagnosis', as: :diagnosable

end

app/models/allergy.rb
class Allergy < ApplicationRecord

  #
  ##Associations
  #
  belongs_to :patient
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord

  enum diagnosis_type: ['Chronic', 'Diagnosis']
  #
  ##Associations
  #
  belongs_to :diagnosable, polymorphic: true

  def described_code
    "#{description} (#{code})"
  end
end

app/models/diagnostic_procedure.rb
class DiagnosticProcedure < ApplicationRecord

  #
  ##Associations
  #
  belongs_to :patient

  def diagnostic_procedure_summary
    "#{description} at #{created_at.strftime('%H:%M')}"
  end
end

app/models/facility.rb
class Facility < ApplicationRecord
end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord
  enum unit: [:mg]
  enum route: [:po, :im, :sc]
  #
  ##Associations
  #
  belongs_to :patient

  belongs_to :order_frequency

  def order_summary
    "#{name} #{dosage} #{route} #{order_frequency.value}"
  end
end

app/models/observation.rb
class Observation < ApplicationRecord

  #
  ##Associations
  #
  belongs_to :admission
end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord
  enum unit: [:hour]
  #
  ##Associations
  #
  has_many(
    :medication_orders,
    dependent: :destroy
  )
end

app/models/patient.rb
class Patient < ApplicationRecord
  enum gender: [:male, :female, :other]
  #
  ##Associations
  #
  has_many(
    :medication_orders,
    dependent: :destroy
  )

  has_many(
    :treatments,
    dependent: :destroy
  )

  has_many :chronic_diagnoses, -> { where(diagnosis_type: 0)}, class_name: 'Diagnosis', as: :diagnosable
  has_many :diagnoses, -> { where(diagnosis_type: 1)}, class_name: 'Diagnosis', as: :diagnosable

  has_many(
    :diagnostic_procedures,
    dependent: :destroy
  )

  has_many(
    :allergies,
    dependent: :destroy
  )

  belongs_to(
    :facility
  )

  has_one(
    :admission
  )

  def self.search(query)
    where("first_name LIKE :search OR last_name LIKE :search OR middle_name LIKE :search", search: "%#{query}%")
  end

  def age
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  def name
    "#{first_name} #{middle_name} #{last_name}"
  end
end

app/models/symptom.rb
class Symptom < ApplicationRecord

  #
  ##Associations
  #
  belongs_to :admission
end

app/models/treatment.rb
class Treatment < ApplicationRecord

  #
  ##Associations
  #
  belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emergency_transfer_controller.rb
class EmergencyTransferController < ApplicationController
  def index
    patients = params[:query].present? ?
                Patient.search(params[:query]) :
                Patient.all
    @patients = patients.paginate(page: params[:page], per_page: 10)
  end

  def show
    @patient = Patient.includes(:facility, :treatments, :allergies, :diagnostic_procedures, :chronic_diagnoses, :diagnoses, medication_orders: [:order_frequency], admission: [:symptoms, :diagnoses]).find_by(id: params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "show",
        layout: "application"
      end
    end
  end
end

app/helpers/admission_helper.rb
module AdmissionHelper
  def admission_diagnoses(admission)
    to_sentence(admission.diagnoses, 'described_code')
  end

  def admission_symptoms(admission)
    to_sentence(admission.symptoms, 'description')
  end

  def admission_observations(admission)
    to_sentence(admission.observations, 'description')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def to_sentence(object, column)
    object.map{ |d| d.send(column.to_sym) }.join(', ')
  end
end

app/helpers/patient_helper.rb
module PatientHelper
  def patient_treatments(patient)
    treatments = patient.treatments.pluck(:description, :necessity)
    treatments.each_with_object([]) { |e, r| r << e.join(' ') }.join(', ')
  end

  def patient_allergies(patient)
    patient.allergies.pluck(:description).join(', ')
  end

  def patient_chronic_conditions(patient)
    to_sentence(patient.chronic_diagnoses, 'described_code')
  end

  def patient_medications_orders(patient)
    to_sentence(patient.medication_orders, 'order_summary')
  end

  def patient_diagnostic_procedures(patient)
    to_sentence(patient.diagnostic_procedures, 'diagnostic_procedure_summary')
  end
end

app/views/emergency_transfer/index.html.erb
<%= content_for :heading, "All Patients" %>
<div class="ml-auto">
  <%= will_paginate @patients %>
</div>
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Patient</th>
      <th>Age</th>
      <th>Admission Date</th>
      <th>Medical Record</th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to patient.name, emergency_transfer_path(patient) %></td>
        <td><%= patient.age %></td>
        <td><%= patient.admission.created_at.strftime('%Y-%m-%d') %></td>
        <td><%= patient.mr.truncate(30) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="ml-auto">
  <%= will_paginate @patients %>
</div>

app/views/emergency_transfer/show.html.erb
<%= content_for :heading do %>
  <%= "Patients summary - #{@patient.name}" %>
<% end %>

<%= content_for :button do %>
  <div class="ml-auto">
    <%= link_to 'Print', emergency_transfer_path(@patient.id, format: :pdf), class: "btn btn-success", target: '_blank' %>
    <%= link_to 'Back', root_path, class: "btn btn-outline-dark" %>
  </div>
<% end %>

<div class="col-12">
  <table class="table table-bordered">
      <tr class="summary-header"><td colspan="4"><b>Emergency Transfer Summary (Form 34L-D)</b></td></tr>

      <tr><td colspan="4"><b>Transferring Facility</b></td></tr>
      <tr>
        <td colspan="1">Name<br /><br />
          <span class="span-color"><%= @patient.facility.name %></span>
        </td>
        <td colspan="3">&nbsp;</td>
      </tr>

      <tr>
        <td colspan="4"><b>Patient Information</b></td>
      </tr>

      <tr>
        <td>First Name<br /><br />
          <span class="span-color"><%= @patient.first_name %></span>
        </td>

        <td>Middle Name<br /><br />
          <span class="span-color"><%= @patient.middle_name %></span>
        </td>

        <td>Last Name<br /><br />
          <span class="span-color"><%= @patient.last_name %></span>
        </td>

        <td>Medical Record (MR)<br /><br />
          <span class="span-color"><%= @patient.mr %></span>
        </td>
      </tr>

      <tr>
        <td colspan="4"><b>Summary</b>
          <br />
          <br />
          This <span class="span-color"><%= @patient.age %></span>
          years old <span class="span-color"><%= @patient.gender %></span>
          was admitted to <span class="span-color"><%= @patient.facility.name %></span>
          on <span class="span-color"><%= @patient.admission.created_at.strftime('%Y-%m-%d') %></span>
          at <span class="span-color"><%= @patient.admission.created_at.strftime('%H:%M') %></span>
          due to <span class="span-color"><%= admission_diagnoses(@patient.admission)%></span>.

          The observed symptoms on admission were
          <span class="span-color"><%= admission_symptoms(@patient.admission)%></span>.

          <span class="span-color"><%= admission_observations(@patient.admission)%></span>.

          Upon asking about known allergies, the patient disclosed
          <span class="span-color"><%= patient_allergies(@patient)%></span>.

          Upon asking about chronic conditions, the patient disclosed
          <span class="span-color"><%= patient_chronic_conditions(@patient)%></span>.

          The patient was administered with
          <span class="span-color"><%= patient_medications_orders(@patient)%></span>.

          The staff performed
          <span class="span-color"><%= patient_diagnostic_procedures(@patient)%></span>.

          Our team proceeded to
          <span class="span-color"><%= patient_treatments(@patient) %></span>.
          </span>
        </td>
      </tr>
  </table>
</div>

app/views/emergency_transfer/show.pdf.erb
<html>
  <head>
      <meta charset="utf-8">
      <link href="https://fonts.googleapis.com/css?family=Helvetica" rel="stylesheet">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
      <style>
        .summary-header td {
          background-color: #dee2e6;
        }

        span.span-color {
          color: #0000ff;
        }
      </style>
  </head>
  <body>
    <div class="content">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <table class="table table-bordered">
              <tr class="summary-header"><td colspan="4"><b>Emergency Transfer Summary (Form 34L-D)</b></td></tr>

              <tr><td colspan="4"><b>Transferring Facility</b></td></tr>
              <tr>
                <td colspan="1">Name<br /><br />
                  <span class="span-color"><%= @patient.facility.name %></span>
                </td>
                <td colspan="3">&nbsp;</td>
              </tr>

              <tr>
                <td colspan="4"><b>Patient Information</b></td>
              </tr>

              <tr>
                <td>First Name<br /><br />
                  <span class="span-color"><%= @patient.first_name %></span>
                </td>

                <td>Middle Name<br /><br />
                  <span class="span-color"><%= @patient.middle_name %></span>
                </td>

                <td>Last Name<br /><br />
                  <span class="span-color"><%= @patient.last_name %></span>
                </td>

                <td>Medical Record (MR)<br /><br />
                  <span class="span-color"><%= @patient.mr %></span>
                </td>
              </tr>

              <tr>
                <td colspan="4"><b>Summary</b>
                  <br />
                  <br />
                  This <span class="span-color"><%= @patient.age %></span>
                  years old <span class="span-color"><%= @patient.gender %></span>
                  was admitted to <span class="span-color"><%= @patient.facility.name %></span>
                  on <span class="span-color"><%= @patient.admission.created_at.strftime('%Y-%m-%d') %></span>
                  at <span class="span-color"><%= @patient.admission.created_at.strftime('%H:%M') %></span>
                  due to <span class="span-color"><%= admission_diagnoses(@patient.admission)%></span>.

                  The observed symptoms on admission were
                  <span class="span-color"><%= admission_symptoms(@patient.admission)%></span>.

                  <span class="span-color"><%= admission_observations(@patient.admission)%></span>.

                  Upon asking about known allergies, the patient disclosed
                  <span class="span-color"><%= patient_allergies(@patient)%></span>.

                  Upon asking about chronic conditions, the patient disclosed
                  <span class="span-color"><%= patient_chronic_conditions(@patient)%></span>.

                  The patient was administered with
                  <span class="span-color"><%= patient_medications_orders(@patient)%></span>.

                  The staff performed
                  <span class="span-color"><%= patient_diagnostic_procedures(@patient)%></span>.

                  Our team proceeded to
                  <span class="span-color"><%= patient_treatments(@patient) %></span>.
                  </span>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/emergency_transfer/transfer_details.html.erb
<div class="content row">
  <table class="table table-bordered">
      <tr class="summary-header"><td colspan="4"><b>Emergency Transfer Summary (Form 34L-D)</b></td></tr>

      <tr><td colspan="4"><b>Transferring Facility</b></td></tr>
      <tr>
        <td colspan="1">Name<br /><br />
          <span style="color: #0000ff"><%= @patient.facility.name %></span>
        </td>
        <td colspan="3">&nbsp;</td>
      </tr>

      <tr>
        <td colspan="4"><b>Patient Information</b></td>
      </tr>

      <tr>
        <td>First Name<br /><br />
          <span style="color: #0000ff"><%= @patient.first_name %></span>
        </td>

        <td>Middle Name<br /><br />
          <span style="color: #0000ff"><%= @patient.middle_name %></span>
        </td>

        <td>Last Name<br /><br />
          <span style="color: #0000ff"><%= @patient.last_name %></span>
        </td>

        <td>Medical Record (MR)<br /><br />
          <span style="color: #0000ff"><%= @patient.mr %></span>
        </td>
      </tr>

      <tr>
        <td colspan="4"><b>Summary</b>
          <br />
          <br />
          This <span style="color: #0000ff"><%= @patient.age %></span>
          years old <span style="color: #0000ff"><%= @patient.gender %></span>
          was admitted to <span style="color: #0000ff"><%= @patient.facility.name %></span>
          on <span style="color: #0000ff"><%= @patient.admission.created_at.strftime('%Y-%m-%d') %></span>
          at <span style="color: #0000ff"><%= @patient.admission.created_at.strftime('%H:%M') %></span>
          due to <span style="color: #0000ff"><%= admission_diagnoses(@patient)%></span>.

          The observed symptoms on admission were
          <span style="color: #0000ff"><%= admission_symptoms(@patient)%></span>.

          <span style="color: #0000ff"><%= admission_observations(@patient)%></span>.

          Upon asking about known allergies, the patient disclosed
          <span style="color: #0000ff"><%= allergies(@patient)%></span>.

          Upon asking about chronic conditions, the patient disclosed
          <span style="color: #0000ff"><%= chronic_conditions(@patient)%></span>.

          The patient was administered with
          <span style="color: #0000ff"><%= medications(@patient)%></span>.

          The staff performed
          <span style="color: #0000ff"><%= diagnostic_procedures(@patient)%></span>.

          Our team proceeded to
          <span style="color: #0000ff"><%= treatments(@patient) %></span>.
          </span>
        </td>
      </tr>
  </table>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Camp Emergency Transfer", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <%= form_tag root_path, method: :get, class: "form-inline my-2 my-lg-0 ml-auto" do %>
      <%= text_field_tag :query, params[:search], placeholder: "Search for patients", class: 'form-control mr-sm-2' %>
      <%= submit_tag "Search", class: 'btn btn-outline-info my-2 my-sm-0' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampEmergencyTransfer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="row">
        <div class="col-12 my-5 d-flex">
          <h3 class="display"><%= yield :heading %></h3>
          <%= yield :button %>
        </div>
          <%= yield %>
        <div>
    </div>
  </body>
</html>